site_name: AI Validation Team
site_description: Documenting the processes of the AI Validation Team at the Ministry of the Interior and Kingdom Relations in The Netherlands.
site_url: https://minbzk.github.io/ai-validation/

copyright: European Union Public License v. 1.2

repo_name: MinBZK/ai-validation
repo_url: https://github.com/MinBZK/ai-validation
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: overrides
  language: en
  palette:
    primary: deep orange
    scheme: slate
  features:
    - content.action.edit
    - content.code.copy
    - navigation.indexes
    - navigation.instant
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest
  icon:
    logo: fontawesome/solid/house
    annotation: fontawesome/solid/circle-info

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - footnotes
  - pymdownx.details
  - admonition
  - attr_list
  - abbr
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MinBZK/ai-validation

extra_css:
  - stylesheets/extra.css

extra_templates:
  - .well-known/security.txt

watch:
  - overrides/

plugins:
  - awesome-pages
  - git-committers:
      repository: minbzk/ai-validation
      branch: main
  - git-revision-date-localized:
      enable_creation_date: true
  - glightbox
  - privacy
  - search

nav:
  - Home: index.md
  - Projects:
    - TAD:
      - projects/tad/index.md
      - Reporting Standard:
        - projects/tad/reporting-standard/index.md
        - projects/tad/reporting-standard/latest.md
        - projects/tad/reporting-standard/0.1a6.md
        - projects/tad/reporting-standard/0.1a5.md
        - projects/tad/reporting-standard/0.1a4.md
        - projects/tad/reporting-standard/0.1a3.md
        - projects/tad/reporting-standard/0.1a2.md
        - projects/tad/reporting-standard/0.1a1.md
        - projects/tad/comparison.md
      - ADRs for TAD:
        - ... | flat | projects/tad/adrs/*
      - Existing tools:
        - ... | flat | projects/tad/existing-tools/comparison/*
        - Checklist:
          - ... | flat | projects/tad/existing-tools/checklists/*
    - LLM Benchmarks:
      - projects/llm-benchmarks/index.md
  - Way of Working:
    - way-of-working/principles.md
    - way-of-working/contributing.md
    - ... | flat | way-of-working/*
    - Onboarding:
      - ... | flat | way-of-working/onboarding/*
    - way-of-working/off-boarding.md
    - way-of-working/decision-log.md
  - ... | adrs/*
  - ... | about/*
